config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'pages#home'
  resources :mentorats , only: [:index, :new, :create, :show, :update, :edit, :destroy]
  resources :prises , only: [:index, :new, :create, :show, :update, :edit, :destroy]
  resources :ambassadeurs , only: [:index, :new, :create, :show, :update, :edit, :destroy]
  get    '/mentions'      => 'pages#mentions'
  get    '/amis'      => 'pages#amis'

end

app/models/ambassadeur.rb
class Ambassadeur < ApplicationRecord
end

app/controllers/ambassadeurs_controller.rb
class AmbassadeursController < ApplicationController
  def index
   @ambassadeur =  Ambassadeur.order(id: :desc)

  end

  def new
    @ambassadeur = Ambassadeur.new # needed to instantiate the form_for
  end

  def create
    @ambassadeur = Ambassadeur.new(ambassadeur_params)
    if @ambassadeur.save!
    redirect_to ambassadeurs_path(@ambassadeur)
    end

    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def edit
    @ambassadeur = Ambassadeur.find(params[:id])
  end

  def update
    @ambassadeur = Ambassadeur.find(params[:id])
    @ambassadeur.update(ambassadeur_params)
    # no need for app/views/restaurants/update.html.erb
    redirect_to ambassadeur_path(@ambassadeur)
  end
  def show
    @ambassadeur = Ambassadeur.find(params[:id])
 end

  def destroy
    @ambassadeur = Ambassadeur.find(params[:id])
    @ambassadeur.destroy
    redirect_to ambassadeurs_path
  end

  private

  def ambassadeur_params
    params.require(:ambassadeur).permit(:img1_a, :img2_a, :img3_a, :img4_a, :img5_a, :img6_a, :img7_a, :img8_a, :img9_a, :img10_a, :paraph1_a, :paraph2_a, :paraph3_a, :paraph4_a, :paraph5_a, :legend1_a, :legend2_a, :legend3_a, :legend4_a, :legend5_a, :legend6_a, :legend7_a, :legend8_a, :legend9_a, :legend10_a, :date_a, :lieu_a, :nom_ambassadeur, :nom_auteur_a, :titre_a, :sous_titre_a, :avatar_img_a, :lien_url1_a, :lien_url2_a, :video_a, :question1,:question2,:question3,:question4,:question5,:question6,:question7,:question8,:question9,:question10,:paraph6_a,:paraph7_a,:paraph8_a,:paraph9_a,:paraph10_a)
  end
end

app/helpers/ambassadeurs_helper.rb
module AmbassadeursHelper
end

app/views/ambassadeurs/edit.html.erb
<div class="d-flex container justify-content-center display-bubble">
  <%= simple_form_for(@ambassadeur) do |f| %>
         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
           <h3 class="title-new">Modifier un ambassadeur</h3>
           <h5>Nom de l'artiste</h5>
          <%= f.input :nom_ambassadeur %>
          <h5>Nom de l'auteur</h5>
          <%= f.input :nom_auteur_a %>
          <h5>Titre de l'article</h5>
          <%= f.input :titre_a %>
          <h5>Sous-titre</h5>
          <%= f.input :sous_titre_a %>
          <h5>Photo de l'artiste</h5>
          <%= f.input :avatar_img_a %>
          <h5>Date de l'article</h5>
           <%= f.input :date_a %>
           <h5>Lieu</h5>
           <%= f.input :lieu_a %>
           <h5>Site internet</h5>
           <%= f.input :lien_url1_a %>
           <h5>Site internet</h5>
           <%= f.input :lien_url2_a %>
           <h5>Vidéo</h5>
           <%= f.input :video_a %>
           <h5>Image 1</h5>
           <%= f.input :img1_a %>
           <%= f.input :img2_a %>
           <%= f.input :img3_a %>
           <%= f.input :img4_a %>
           <%= f.input :img5_a %>
           <%= f.input :img6_a %>
           <%= f.input :img7_a %>
           <%= f.input :img8_a %>
           <%= f.input :img9_a %>
           <%= f.input :img10_a %>
           <h5>Legendes</h5>
           <%= f.input :legend1_a %>
           <%= f.input :legend2_a %>
           <%= f.input :legend3_a %>
           <%= f.input :legend4_a %>
           <%= f.input :legend5_a %>
           <%= f.input :legend6_a %>
           <%= f.input :legend7_a %>
           <%= f.input :legend8_a %>
           <%= f.input :legend9_a %>
           <%= f.input :legend10_a %>
           <h5>Introduction</h5>
           <%= f.input :introduction_a %>
           <h5>Q1</h5>
           <%= f.input :question1 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph1_a %>
           <h5>Q2</h5>
           <%= f.input :question2 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph2_a %>
           <h5>Q3</h5>
           <%= f.input :question3 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph3_a %>
           <h5>Q4</h5>
           <%= f.input :question4 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph4_a %>
           <h5>Q5</h5>
           <%= f.input :question5 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph5_a %>
           <h5>Q6</h5>
           <%= f.input :question6 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph6_a %>
           <h5>Q7</h5>
           <%= f.input :question7 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph7_a %>
           <h5>Q8</h5>
           <%= f.input :question8 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph8_a %>
           <h5>Q9</h5>
           <%= f.input :question9 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph9_a %>
           <h5>Q10</h5>
           <%= f.input :question10 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph10_a %>

         </div>

         <div class="form-actions">
           <%= f.submit "Save changes", class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>
</div>

app/views/ambassadeurs/index.html.erb
<%= render "components/header" %>
<div class="bandeau">
<br>
<h1 class="t1_bandeau">Ambassadeur</h1>
<br>
<h2 class="t_bandeau">Portraits d’artistes engagés
dans la culture.</h2>
</div>

<div class="index_2">
<% if user_signed_in? %>
<div class="btn btn-light btn-banner-p"><%= link_to "Ajouter un ambassadeur", new_ambassadeur_path %></div>
<% end %>
<div class="display-grid-card">
  <% @ambassadeur.each do |ambassadeur| %>
    <div class="prise">
      <% if user_signed_in? %>
        <div class ="">
          <%= link_to 'Supprimer', ambassadeur_path(ambassadeur),
            method: :delete,
            data: { confirm: 'Êtes-vous certain de vouloir supprimer?' } %>
          <%= link_to "Editer", edit_ambassadeur_path(ambassadeur.id)%>
        </div>
      <% end %>
          <div class="linear">
            <%= link_to(image_tag("#{ambassadeur.img1_a}", alt: "Art Prise, Place à la culture de demain!"), ambassadeur_path(ambassadeur.id)) %>
            <div class="flex_a">
              <h6 class=""><%= ambassadeur.nom_ambassadeur%></h6>
              <h5 id="info_a"> Le <%= ambassadeur.date_a %> à <%= ambassadeur.lieu_a %></h5>
            </div>
            <div class="img-avatar-a">
            <%= link_to(image_tag("#{ambassadeur.avatar_img_a}", alt: "Art Prise, Place à la culture de demain!"), ambassadeur_path(ambassadeur.id)) %>
            </div>

          </div>
    </div>
     <% end %>
  </div>

</div>
<%= render "components/footer" %>

app/views/ambassadeurs/new.html.erb
<div class="d-flex container justify-content-center display-bubble">
    <%= simple_form_for(@ambassadeur) do |f| %>
         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
          <h3 class="title-new">Ajouter un Ambassadeur</h3>
          <h5>Nom de l'artiste</h5>
          <%= f.input :nom_ambassadeur %>
          <h5>Nom de l'auteur</h5>
          <%= f.input :nom_auteur_a %>
          <h5>Titre de l'article</h5>
          <%= f.input :titre_a %>
          <h5>Sous-titre</h5>
          <%= f.input :sous_titre_a %>
          <h5>Photo de l'artiste</h5>
          <%= f.input :avatar_img_a %>
          <h5>Date de l'article</h5>
           <%= f.input :date_a %>
           <h5>Lieu</h5>
           <%= f.input :lieu_a %>
           <h5>Site internet</h5>
           <%= f.input :lien_url1_a %>
           <h5>Site internet</h5>
           <%= f.input :lien_url2_a %>
           <h5>Vidéo</h5>
           <%= f.input :video_a %>
           <h5>Image 1</h5>
           <%= f.input :img1_a %>
           <%= f.input :img2_a %>
           <%= f.input :img3_a %>
           <%= f.input :img4_a %>
           <%= f.input :img5_a %>
           <%= f.input :img6_a %>
           <%= f.input :img7_a %>
           <%= f.input :img8_a %>
           <%= f.input :img9_a %>
           <%= f.input :img10_a %>
           <h5>Legendes</h5>
           <%= f.input :legend1_a %>
           <%= f.input :legend2_a %>
           <%= f.input :legend3_a %>
           <%= f.input :legend4_a %>
           <%= f.input :legend5_a %>
           <%= f.input :legend6_a %>
           <%= f.input :legend7_a %>
           <%= f.input :legend8_a %>
           <%= f.input :legend9_a %>
           <%= f.input :legend10_a %>
           <h5>Introduction</h5>
           <%= f.input :introduction_a %>
           <h5>Q1</h5>
           <%= f.input :question1 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph1_a %>
           <h5>Q2</h5>
           <%= f.input :question2 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph2_a %>
           <h5>Q3</h5>
           <%= f.input :question3 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph3_a %>
           <h5>Q4</h5>
           <%= f.input :question4 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph4_a %>
           <h5>Q5</h5>
           <%= f.input :question5 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph5_a %>
           <h5>Q6</h5>
           <%= f.input :question6 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph6_a %>
           <h5>Q7</h5>
           <%= f.input :question7 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph7_a %>
           <h5>Q8</h5>
           <%= f.input :question8 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph8_a %>
           <h5>Q9</h5>
           <%= f.input :question9 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph9_a %>
           <h5>Q10</h5>
           <%= f.input :question10 %>
           <h5>Paragraphe</h5>
           <%= f.input :paraph10_a %>


         </div>

         <div class="form-actions">
           <%= f.button :submit, class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>

app/views/ambassadeurs/show.html.erb
<%= render "components/header" %>
<div id="index_m index_">
<div class="card-category image1 image2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @ambassadeur.img1_a %>)">
  <% if @ambassadeur.avatar_img_a != ""  %>
  <%= image_tag("#{@ambassadeur.avatar_img_a}") %>
  <% end %>
  </div>
</div>
<div id="index_m">
<div id="index_p">
<h1 class="title-pp" id="ambassadeur-name"><%= @ambassadeur.nom_ambassadeur %></h1>
<p id="paraph-ambassadeur">Par - <%= @ambassadeur.nom_auteur_a %>, le <%= @ambassadeur.date_a %></p>
<% if @ambassadeur.video_a != ""  %>
  <iframe width="930" height="560"
    src="<%= @ambassadeur.video_a %>"
    frameborder="0"
    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen>
  </iframe>
   <% end %>
  <% if @ambassadeur.introduction_a != ""  %>
  <p class="intro"><%= @ambassadeur.introduction_a %></p>
  <% end %>
  <% if @ambassadeur.question1 != ""  %>
  <p id="paraph-ambassadeur" class="question_a"><%= @ambassadeur.question1 %></p>
  <% end %>
  <% if @ambassadeur.paraph1_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph1_a %></p>
  <% end %>
  <br>
  <% if @ambassadeur.img1_a != ""  %>
  <%= image_tag("#{@ambassadeur.img1_a}") %>
  <% end %>
<% if @ambassadeur.legend1_a != ""  %>
  <h5 id="paraph-ambassadeur"><%= @ambassadeur.legend1_a %></h5>
  <% end %>
  <br>
  <% if @ambassadeur.question2 != ""  %>
  <p id="paraph-ambassadeur" class="question_a"><%= @ambassadeur.question2 %></p>
  <% end %>
  <% if @ambassadeur.paraph2_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph2_a %></p>
  <% end %>
  <br>
  <% if @ambassadeur.img2_a != ""  %>
  <%= image_tag("#{@ambassadeur.img2_a}") %>
  <% end %>
  <% if @ambassadeur.legend2_a != ""  %>
  <h5 id="paraph-ambassadeur"><%= @ambassadeur.legend2_a %></h5>
  <% end %>
  <br>
  <% if @ambassadeur.question3 != ""  %>
  <p id="paraph-ambassadeur" class="question_a"><%= @ambassadeur.question3 %></p>
  <% end %>
  <% if @ambassadeur.paraph3_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph3_a %></p>
  <% end %>
  <br>
  <% if @ambassadeur.img3_a != ""  %>
  <%= image_tag("#{@ambassadeur.img3_a}") %>
  <% end %>
  <% if @ambassadeur.legend3_a != ""  %>
  <h5 id="paraph-ambassadeur"><%= @ambassadeur.legend3_a %></h5>
  <% end %>
  <br>
  <% if @ambassadeur.question4 != ""  %>
  <p id="paraph-ambassadeur" class="question_a"><%= @ambassadeur.question4 %></p>
  <% end %>
  <% if @ambassadeur.paraph4_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph4_a %></p>
  <% end %>
  <br>
  <% if @ambassadeur.img4_a != ""  %>
  <%= image_tag("#{@ambassadeur.img4_a}") %>
  <% end %>
  <% if @ambassadeur.legend4_a != ""  %>
  <h5 id="paraph-ambassadeur"><%= @ambassadeur.legend4_a %></h5>
  <% end %>
  <br>
  <% if @ambassadeur.question5 != ""  %>
  <p id="paraph-ambassadeur" class="question_a"><%= @ambassadeur.question5 %></p>
  <% end %>
  <% if @ambassadeur.paraph5_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph5_a %></p>
  <% end %>
  <br>
   <% if @ambassadeur.img5_a != ""  %>
   <%= image_tag("#{@ambassadeur.img5_a}") %>
   <% end %>
   <% if @ambassadeur.legend5_a!= ""  %>
  <h5 id="paraph-ambassadeur"><%= @ambassadeur.legend5_a %></h5>
  <% end %>
  <br>
  <% if @ambassadeur.question6 != ""  %>
  <p id="paraph-ambassadeur" class="question_a"><%= @ambassadeur.question6 %></p>
  <% end %>
  <% if @ambassadeur.paraph6_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph6_a %></p>
  <% end %>
  <br>
  <% if @ambassadeur.img6_a != ""  %>
  <%= image_tag("#{@ambassadeur.img6_a}") %>
  <% end %>
<% if @ambassadeur.legend6_a != ""  %>
  <h5 id="paraph-ambassadeur"><%= @ambassadeur.legend6_a %></h5>
  <% end %>
  <br>
  <% if @ambassadeur.question7 != ""  %>
  <p id="paraph-ambassadeur" class="question_a"><%= @ambassadeur.question7 %></p>
  <% end %>
  <% if @ambassadeur.paraph7_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph7_a %></p>
  <% end %>
  <br>
  <% if @ambassadeur.img7_a != ""  %>
  <%= image_tag("#{@ambassadeur.img7_a}") %>
  <% end %>
  <% if @ambassadeur.legend7_a != ""  %>
  <h5 id="paraph-ambassadeur"><%= @ambassadeur.legend7_a %></h5>
  <% end %>
  <br>
  <% if @ambassadeur.question8 != ""  %>
  <p id="paraph-ambassadeur" class="question_a" class="question_a"><%= @ambassadeur.question8 %></p>
  <% end %>
  <% if @ambassadeur.paraph8_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph8_a %></p>
  <% end %>
  <br>
  <% if @ambassadeur.img8_a != ""  %>
  <%= image_tag("#{@ambassadeur.img8_a}") %>
  <% end %>
  <% if @ambassadeur.legend8_a != ""  %>
  <h5 id="paraph-ambassadeur"><%= @ambassadeur.legend8_a %></h5>
  <% end %>
  <br>
  <% if @ambassadeur.question9 != ""  %>
  <p id="paraph-ambassadeur" class="question_a"><%= @ambassadeur.question9 %></p>
  <% end %>
  <% if @ambassadeur.paraph9_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph9_a %></p>
  <% end %>
  <br>
  <% if @ambassadeur.img9_a != ""  %>
  <%= image_tag("#{@ambassadeur.img9_a}") %>
  <% end %>
  <% if @ambassadeur.legend9_a != ""  %>
  <h5 id="paraph-ambassadeur"><%= @ambassadeur.legend9_a %></h5>
  <% end %>
  <br>
  <% if @ambassadeur.question10 != ""  %>
  <p id="paraph-ambassadeur" class="question_a"><%= @ambassadeur.question10 %></p>
  <% end %>
  <% if @ambassadeur.paraph10_a != ""  %>
  <p id="paraph-ambassadeur"><%= @ambassadeur.paraph10_a %></p>
  <% end %>
  <br>
   <% if @ambassadeur.img10_a != ""  %>
   <%= image_tag("#{@ambassadeur.img5_a}") %>
   <% end %>
   <% if @ambassadeur.legend10_a!= ""  %>
  <h5><%= @ambassadeur.legend10_a %></h5>
  <% end %>
</div>


</div>


<br>
<br>
<%= render "components/footer" %>