config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'pages#home'
  resources :mentorats , only: [:index, :new, :create, :show, :update, :edit, :destroy]
  resources :prises , only: [:index, :new, :create, :show, :update, :edit, :destroy]
  resources :ambassadeurs , only: [:index, :new, :create, :show, :update, :edit, :destroy]
  get    '/mentions'      => 'pages#mentions'
  get    '/amis'      => 'pages#amis'

end

app/models/mentorat.rb
class Mentorat < ApplicationRecord
end

app/controllers/mentorats_controller.rb
class MentoratsController < ApplicationController
   def index
   @mentorat =  Mentorat.order(id: :desc)

  end

  def new
    @mentorat = Mentorat.new # needed to instantiate the form_for
  end

  def create
    @mentorat = Mentorat.new(mentorat_params)
    if @mentorat.save!
    redirect_to mentorats_path(@mentorat)
    end

    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def edit
    @mentorat = Mentorat.find(params[:id])
  end

  def update
    @mentorat = Mentorat.find(params[:id])
    @mentorat.update(mentorat_params)
    # no need for app/views/restaurants/update.html.erb
    redirect_to mentorat_path(@mentorat)
  end
  def show
    @mentorat = Mentorat.find(params[:id])
 end

  def destroy
    @mentorat = Mentorat.find(params[:id])
    @mentorat.destroy
    redirect_to mentorats_path
  end

  private

  def mentorat_params
    params.require(:mentorat).permit(:video_m, :video_m2, :img_m1, :img_m2, :img_m3, :img_m4, :img_m5, :legend_m1, :legend_m2, :legend_m3, :legend_m4, :legend_m5, :avatar_img_m1, :avatar_img_m2, :avatar_img_m3, :avatar_img_m4, :avatar_img_m5, :avatar_img_m6, :avatar_img_m7, :avatar_img_m8, :avatar_img_m9, :avatar_img_m10, :avatar_name_m1, :avatar_name_m2, :avatar_name_m3, :avatar_name_m4, :avatar_name_m5, :avatar_name_m6, :avatar_name_m7, :avatar_name_m8, :avatar_name_m9, :avatar_name_m10, :avatar_url_m1, :avatar_url_m2, :avatar_url_m3, :avatar_url_m4, :avatar_url_m5, :avatar_url_m6, :avatar_url_m7, :avatar_url_m8, :avatar_url_m9, :avatar_url_m10, :avatar_titre_m1, :avatar_titre_m2, :avatar_titre_m3, :avatar_titre_m4, :avatar_titre_m5, :avatar_titre_m6, :avatar_titre_m7, :avatar_titre_m8, :avatar_titre_m9, :avatar_titre_m10, :paraph_m1, :paraph_m2, :paraph_m3, :paraph_m4, :titre_m, :sous_titre_m, :date_m, :lieu_m, :lien_url1_m, :lien_url2_m)
 end
end

app/helpers/mentorats_helper.rb
module MentoratsHelper
end

app/views/mentorats/edit.html.erb
    <div class="d-flex container justify-content-center display-bubble">
    <%= simple_form_for(@mentorat) do |f| %>
         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
           <h3 class="title-new">Modifier un mentorat</h3>
                  <h5>Titre</h5>
           <%= f.input :titre_m %>
           <h5>Sous-titre</h5>
           <%= f.input :sous_titre_m %>
           <h5>Date</h5>
           <%= f.input :date_m %>
           <h5>Lieu</h5>
           <%= f.input :lieu_m %>
           <h5>Site internet</h5>
           <%= f.input :lien_url1_m %>
           <%= f.input :lien_url2_m %>
           <h5>Vidéo 1 et 2</h5>
           <%= f.input :video_m %>
           <%= f.input :video_m2 %>

           <h5>Paragraphes</h5>
           <%= f.input :paraph_m1 %>
           <%= f.input :paraph_m2 %>
           <%= f.input :paraph_m3 %>
           <%= f.input :paraph_m4 %>

           <h5>Images</h5>
           <%= f.input :img_m1 %>
           <%= f.input :img_m2 %>
           <%= f.input :img_m3 %>
           <%= f.input :img_m4 %>
           <%= f.input :img_m5 %>
           <h5>Légendes</h5>
           <%= f.input :legend_m1 %>
           <%= f.input :legend_m2 %>
           <%= f.input :legend_m3 %>
           <%= f.input :legend_m4 %>
           <%= f.input :legend_m5 %>

           <h5>Participants img</h5>
           <%= f.input :avatar_img_m1 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m1 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m1 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m1 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m2 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m2 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m2 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m2 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m3 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m3 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m3 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m3 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m4 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m4 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m4 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m4 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m5 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m5 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m5 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m5 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m6 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m6 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m6 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m6 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m7 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m7 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m7 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m7 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m8 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m8 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m8 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m8 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m9 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m9 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m9 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m9 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m10 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m10 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m10 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m10 %>

         </div>

         <div class="form-actions">
           <%= f.submit "Save changes", class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>

app/views/mentorats/index.html.erb
<%= render "components/header" %>
<div class="bandeau">
<br>
<h1 class="t1_bandeau">Mentorat</h1>
<br>
<h2 class="t_bandeau">Un artiste porteur d'un projet culturel
soutenu pendant 1 an.</h2>
</div>


<div class="index_2">
<% if user_signed_in? %>
<div class="btn btn-light btn-banner-p"><%= link_to "Ajouter un mentorat", new_mentorat_path %></div>
<% end %>

<div class="display-grid-card">
  <% @mentorat.each do |mentorat| %>
    <div class="prise">
      <% if user_signed_in? %>
        <div class ="">
          <%= link_to 'Supprimer', mentorat_path(mentorat),
            method: :delete,
            data: { confirm: 'Êtes-vous certain de vouloir supprimer?' } %>
          <%= link_to "Editer", edit_mentorat_path(mentorat.id)%>
        </div>
      <% end %>
          <div class="linear">
            <%= link_to(image_tag("#{mentorat.img_m1}", alt: "Art Prise, Place à la culture de demain!"), mentorat_path(mentorat.id)) %>
            <h1><%= mentorat.titre_m %></h1>
            <div class="info_p">
            <h4 class=""><%= mentorat.date_m %></h4>
            <h5 class=""><%= mentorat.lieu_m %></h5>
            </div>
          </div>
    </div>
     <% end %>
  </div>

</div>
<%= render "components/footer" %>

app/views/mentorats/new.html.erb
<div class="d-flex container justify-content-center display-bubble">
    <%= simple_form_for(@mentorat) do |f| %>

         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
          <h3 class="title-new">Ajouter un Mentorat</h3>
          <h5>Titre</h5>
           <%= f.input :titre_m %>
           <h5>Sous-titre</h5>
           <%= f.input :sous_titre_m %>
           <h5>Date</h5>
           <%= f.input :date_m %>
           <h5>Lieu</h5>
           <%= f.input :lieu_m %>
           <h5>Site internet</h5>
           <%= f.input :lien_url1_m %>
           <%= f.input :lien_url2_m %>
           <h5>Vidéo 1 et 2</h5>
           <%= f.input :video_m %>
           <%= f.input :video_m2 %>

           <h5>Paragraphes</h5>
           <%= f.input :paraph_m1 %>
           <%= f.input :paraph_m2 %>
           <%= f.input :paraph_m3 %>
           <%= f.input :paraph_m4 %>

           <h5>Images</h5>
           <%= f.input :img_m1 %>
           <%= f.input :img_m2 %>
           <%= f.input :img_m3 %>
           <%= f.input :img_m4 %>
           <%= f.input :img_m5 %>
           <h5>Légendes</h5>
           <%= f.input :legend_m1 %>
           <%= f.input :legend_m2 %>
           <%= f.input :legend_m3 %>
           <%= f.input :legend_m4 %>
           <%= f.input :legend_m5 %>

           <h5>Participants img</h5>
           <%= f.input :avatar_img_m1 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m1 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m1 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m1 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m2 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m2 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m2 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m2 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m3 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m3 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m3 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m3 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m4 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m4 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m4 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m4 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m5 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m5 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m5 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m5 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m6 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m6 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m6 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m6 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m7 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m7 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m7 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m7 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m8 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m8 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m8 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m8 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m9 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m9 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m9 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m9 %>
           <h5>Participants img</h5>
           <%= f.input :avatar_img_m10 %>
           <h5>Participants Nom</h5>
           <%= f.input :avatar_name_m10 %>
           <h5>Participants Rôle</h5>
           <%= f.input :avatar_titre_m10 %>
           <h5>Participants Site internet</h5>
           <%= f.input :avatar_url_m10 %>

         </div>

         <div class="form-actions">
           <%= f.button :submit, class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>
</div>

app/views/mentorats/show.html.erb
<%= render "components/header" %>
<br>
<br>
<div id="index_m">
<div id="index_p">
<h1 class="title-pp"><%= @mentorat.titre_m %></h1>
<% if @mentorat.img_m1 != ""  %>
  <iframe width="930" height="560"
    src="<%= @mentorat.video_m %>"
    frameborder="0"
    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen>
  </iframe>
   <% end %>
  <br>
  <h1 class="title-pp">À PROPOS</h1>
  <% if @mentorat.paraph_m1 != ""  %>
  <p><%= @mentorat.paraph_m1 %></p>
  <% end %>
  <br>
  <% if @mentorat.img_m1 != ""  %>
  <%= image_tag("#{@mentorat.img_m1}") %>
  <% end %>
<% if @mentorat.legend_m1 != ""  %>
  <h5><%= @mentorat.legend_m1 %></h5>
  <% end %>
<br>
  <br>
  <% if @mentorat.paraph_m2 != ""  %>
  <p><%= @mentorat.paraph_m2 %></p>
  <% end %>
  <br>
  <% if @mentorat.img_m2 != ""  %>
  <%= image_tag("#{@mentorat.img_m2}") %>
  <% end %>
  <% if @mentorat.legend_m2 != ""  %>
  <h5><%= @mentorat.legend_m2 %></h5>
  <% end %>
  <br>
  <% if @mentorat.paraph_m3 != ""  %>
  <p><%= @mentorat.paraph_m3 %></p>
  <% end %>
  <br>
  <% if @mentorat.img_m3 != ""  %>
  <%= image_tag("#{@mentorat.img_m3}") %>
  <% end %>
  <% if @mentorat.legend_m3 != ""  %>
  <h5><%= @mentorat.legend_m3 %></h5>
  <% end %>
  <br>
  <% if @mentorat.img_m4 != ""  %>
  <%= image_tag("#{@mentorat.img_m4}") %>
  <% end %>
  <% if @mentorat.legend_m4 != ""  %>
  <h5><%= @mentorat.legend_m4 %></h5>
  <% end %>
  <br>
   <% if @mentorat.img_m5 != ""  %>
   <%= image_tag("#{@mentorat.img_m5}") %>
   <% end %>
   <% if @mentorat.legend_m5!= ""  %>
  <h5><%= @mentorat.legend_m5 %></h5>
  <% end %>
<br>
  <h1 class="title-pp">ÉQUIPE</h1>
  <% if @mentorat.paraph_m4 != ""  %>
  <p><%= @mentorat.paraph_m4 %></p>
  <% end %>
</div>

<div  id="title-p">
<div class="grid-avatar">
<div id="avatar-p">
  <% if @mentorat.avatar_img_m1 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m1}") %>
  <% end %>
 <% if @mentorat.avatar_name_m1 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m1%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m1 != ""  %>
  <p><%= @mentorat.avatar_titre_m1%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m1 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m1%></div>
  <% end %>
</div>
<div id="avatar-p">
  <% if @mentorat.avatar_img_m2 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m2}") %>
  <% end %>
 <% if @mentorat.avatar_name_m2 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m2%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m2 != ""  %>
  <p><%= @mentorat.avatar_titre_m2%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m2 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m2%></div>
  <% end %>
</div>
<div id="avatar-p">
  <% if @mentorat.avatar_img_m3 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m3}") %>
  <% end %>
 <% if @mentorat.avatar_name_m3 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m3%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m3 != ""  %>
  <p><%= @mentorat.avatar_titre_m3%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m3 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m3%></div>
  <% end %>
</div>
<div id="avatar-p">
  <% if @mentorat.avatar_img_m4 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m4}") %>
  <% end %>
 <% if @mentorat.avatar_name_m4 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m4%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m4 != ""  %>
  <p><%= @mentorat.avatar_titre_m4%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m4 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m4%></div>
  <% end %>
</div>
<div id="avatar-p">
  <% if @mentorat.avatar_img_m5 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m5}") %>
  <% end %>
 <% if @mentorat.avatar_name_m5 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m5%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m5 != ""  %>
  <p><%= @mentorat.avatar_titre_m5%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m5 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m5%></div>
  <% end %>
</div>
<div id="avatar-p">
  <% if @mentorat.avatar_img_m6 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m6}") %>
  <% end %>
 <% if @mentorat.avatar_name_m6 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m6%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m6 != ""  %>
  <p><%= @mentorat.avatar_titre_m6%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m6 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m6%></div>
  <% end %>
</div>
<div id="avatar-p">
  <% if @mentorat.avatar_img_m7 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m7}") %>
  <% end %>
 <% if @mentorat.avatar_name_m7 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m7%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m7 != ""  %>
  <p><%= @mentorat.avatar_titre_m7%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m7 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m7%></div>
  <% end %>
</div>
<div id="avatar-p">
  <% if @mentorat.avatar_img_m8 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m8}") %>
  <% end %>
 <% if @mentorat.avatar_name_m8 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m8%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m8 != ""  %>
  <p><%= @mentorat.avatar_titre_m8%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m8 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m8%></div>
  <% end %>
</div>
<div id="avatar-p">
  <% if @mentorat.avatar_img_m9 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m9}") %>
  <% end %>
 <% if @mentorat.avatar_name_m9 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m9%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m9 != ""  %>
  <p><%= @mentorat.avatar_titre_m9%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m9 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m9%></div>
  <% end %>
</div>
<div id="avatar-p">
  <% if @mentorat.avatar_img_m10 != ""  %>
  <%= image_tag("#{@mentorat.avatar_img_m10}") %>
  <% end %>
 <% if @mentorat.avatar_name_m10 != ""  %>
  <p class="avatar-titre"><%= @mentorat.avatar_name_m10%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m10 != ""  %>
  <p><%= @mentorat.avatar_titre_m10%></p>
  <% end %>
   <% if @mentorat.avatar_titre_m10 != ""  %>
  <div class="plusinfo"><%= link_to "En savoir plus", @mentorat.avatar_url_m10%></div>
  <% end %>
</div>
</div>
</div>
</div>

<br>
<br>
<%= render "components/footer" %>